### PR TITLE
Add Dockerfile

### LINKED ISSUE #16: Docker Instance
Several people who wish to self-host this want to run this service inside Docker.

I'm not sure if this is doable but at least there's `docker-compose.yml` that exposes port based on .env config
 and `.certs` mounted (for SSL cache files).

After that I will publish the image in the next major release.

### PR DESCRIPTION
**Pull request by djbe**
Fixes #16.

## Dockerfile

- Multi-stage build, with 2 final stages, one for each command we want to run (app or stat).
- I've added `ENV`s as needed, with default values corresponding to what I found in the codebase.
- A volume is declared for the `.certs` folder. Docker will create a volume on the fly, but users can provide a local mount point if preferred (see below).
- Everything runs as user `nobody` for better security.

## Build

This adds a dockerfile for hosting both the `app` itself and the `stat` service. You can build it using:
- App: `docker build --tag forward-domain .`
- Stat: `docker build --target=stat --tag forward-domain-stat  .`

To provide a specific `node` version (besides the default `lts`), add ` --build-arg NODE_VERSION=…`.

## Run

Then run it using something like:
```bash
docker run -p 80:8080 -it --env-file .env -v /local-path-to-your/.certs:/app/.certs forward-domain
```

- Make sure to expose the ports you need.
- The env-file argument is optional and should point to an actual file. You can also inject env parameters one by one.
- The volume mount point is recommended so you don't lose data. It should be shared between instances of the `app` and `stat` containers, so the latter can provide accurate information.

## Notes

- I didn't bother adding a target for the development environment as that would involve more dependencies. If anyone wants to tackle that, feel free to do so 😉 
- The name/tags in the build commands are just examples. You probably want something like `forward-domain:version` and `forward-domain:version-stat`. Or maybe not, I honestly don't know which is better.

### CODE REVIEW

**Comment by djbe** [comment]
Forgot to mention: I've tested this locally with the `stat` target, that works. Haven't checked the normal `app` locally, as I have no idea how to test that 😅 

So @willnode  you may want to verify this on your device, as you probably know how to do that.

**Comment by willnode** [comment]
Thank you! I'll try testing it tonight.

For stat itself, I plan to incorporate it into the app itself because I plan to migrate caches to SQLite instead of raw files for next breaking release. This still gone to `.certs` folder so no changes for volumes in that.

**Comment by willnode** [comment]
Hello @djbe. There are recent developments that optimizes this docker build:

1. `pem` is removed so `openssl` binaries is no longer needed.
2. `stat.js` is removed it's now merged with `app.js` and controlled with a new optional envar `HOME_DOMAIN`.
3.  The build image should use `node:<version>-alpine` because I added `sqlite` into deps and `ubuntu` uses GCC while `alpine` uses MUSL so the bindings isn't compatible.

After these changes I can run the app inside docker. These are how i'm testing it:

```sh
docker build --tag forward-domain .
docker run --net=host -e NODE_ENV=test -it -v ./.certs:/app/.certs forward-domain
```

```sh
# test/tools.test.sh
dnsserver &
P1=$!
PEBBLE_WFE_NONCEREJECT=0 pebble -dnsserver 127.0.0.1:1053 -config pebble-config.json &
P2=$!
sleep 2
curl -v --connect-to r.forwarddomain.net:80:localhost:8080 http://r.forwarddomain.net
curl -vk --connect-to r.forwarddomain.net:443:localhost:8443 https://r.forwarddomain.net
kill -9 $P1 $P2
```

**Comment by djbe** [comment]
Adapted to the requested changes, kept the extra base stage for now, could be useful later for a testing stage. 

Also taken the liberty of adding a GH workflow to publish the docker file, based on some workflows I have myself. Tried adding a thing for labeling both the latest tag & the version tag (the metadata step), hopefully that works 🤞

**Review by willnode — APPROVED** [review]
Tested, LGTM

**Pull request merged**
