### PR TITLE
Reload .env file on change without restarting the application

### PR DESCRIPTION
**Pull request by DeBuXer**
With this update, the application now automatically reloads environment variables from the .env file whenever changes are made. This eliminates the need to restart the application when updating an environment variable.

### CODE REVIEW

**Comment by willnode** [comment]
This is good and I can think some actual use case, but you need to clear all variables from util.js to invalidate all config that read from envar. You can create a function in util.js to clear these.

**Review by willnode — COMMENTED** [review]
Please add a function to invalidate all config in util.js

**Review by willnode — CHANGES_REQUESTED** [review]
Please add a function to invalidate all config in util.js

**Comment by DeBuXer** [comment]
I have added a clearConfig() function, but I'm not 100% sure if this is what you meant. If this isn't what you had in mind, could you please clarify what you mean exactly?

Thanks!

**Comment by willnode** [comment]
This is correct. Because all reads from process.env are cached. Because it's set null all variables will be forced to be reset again in each util function.

**Comment by willnode** [comment]
Can you try solve merge conflict before I approve this?

**Comment by DeBuXer** [comment]
Absolutely! I'm just going to wait to resolve the merge conflict until [MR29](https://github.com/willnode/forward-domain/pull/29) is merged as well. Otherwise, I'll end up with another merge conflict there later :)

**Comment by DeBuXer** [comment]
I think the branch is up-to-date now, all merge conflicts are solved.

**Review by willnode — APPROVED** [review]

**Pull request merged**
